# services:
#   mongodb:
#     image: mongo:6.0
#     ports:
#       - "27017:27017"
#     command: mongod --replSet rs0
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=admin
#       - MONGO_INITDB_ROOT_PASSWORD=password
#     volumes:
#       - mongodb_data:/data/db
#     networks:
#       - mongo-network
#     healthcheck:
#       test: |
#         mongosh --eval "try { rs.status().ok } catch (e) { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'mongodb:27017' }] }).ok }"
#       interval: 10s
#       timeout: 10s
#       retries: 5
#       start_period: 10s
#   mongo-express:
#     image: mongo-express
#     # restart: on-failure
#     ports:
#       - "8081:8081"
#     environment:
#       - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
#       - ME_CONFIG_MONGODB_ADMINPASSWORD=password
#       - ME_CONFIG_BASICAUTH_USERNAME=admin
#       - ME_CONFIG_BASICAUTH_PASSWORD=password
#       - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
#       - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
#       - ME_CONFIG_OPTIONS_EDITORTHEME=blackboard
#       - ME_CONFIG_MONGODB_SERVER=mongodb
#       - ME_CONFIG_MONGODB_PORT=27017
#       - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/?replicaSet=rs0
#     networks:
#       - mongo-network
#     depends_on:
#       mongodb:
#         condition: service_healthy

# volumes:
#   mongodb_data:

# networks:
#   mongo-network:
#     driver: bridge

services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    command: mongod --replSet rs0 --auth --keyFile /etc/mongo-keyfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-keyfile:/etc/mongo-keyfile:ro
    networks:
      - mongo-network
    healthcheck:
      test: |
        mongosh --username admin --password password --authenticationDatabase admin --eval "try { rs.status().ok } catch (e) { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'mongodb:27017' }] }).ok }"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_OPTIONS_EDITORTHEME=blackboard
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/admin?authSource=admin&replicaSet=rs0
    networks:
      - mongo-network
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data:

networks:
  mongo-network:
    driver: bridge
