version: "3.8"
services:
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 4000:80
