services:
  redis-stack:
    image: redis/redis-stack
    container_name: redis-stack
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./data:/data
    networks:
      - redis-stack-network

networks:
  redis-stack-network:
    driver: bridge

volumes:
  redis-stack-data:
    driver: local
